resources:
  - type: recipe
    path: example/recipes/homebrew.yml
  - type: recipe
    path: example/recipes/homebrew_cask.yml
  - type: recipe
    path: example/recipes/dotfiles.yml.erb
  - type: nothing
    notify:
      - handler_test
  - type: nothing
    notify:
      - handler_test
handlers:
  - id: handler_test
    type: nothing
