resources:
  - type: remote_file
    source: README.md
    destination: /tmp/README.md
  - type: file
    path: /tmp/README.md
    content: foo
  - type: user
    name: test
    password: test
    home: /Users/test
    shell: /bin/bash
  - type: directory
    path: /Users/test
    owner: test
