resources:
  - type: remote_file
    source: README.md
    destination: /tmp/README.md
  - type: file
    path: /tmp/README.md
    content: foo
  - type: user
    name: test
    password: test
    home: /Users/test
    shell: /bin/bash
  - type: directory
    path: /home/test
    owner: test
  - type: template
    source: example/template.erb
    destination: /tmp/template_test
  - type: group
    name: wheel
