resources:
  - type: user
    name: kit
    password: kit
    home: /home/kit
    shell: /bin/bash
  - type: group
    name: wheel
  - type: user
    name: kit
    group: wheel
  - type: directory
    path: /home/kit/.ssh
    mode: 0700
  - type: line
    path: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
