hosts:
  - localhost
ssh: false
elements:
  - name: install_mysql
    type: homebrew
    package: mysql
    status: installed
  - name: install_redis
    type: homebrew
    package: redis
    status: installed
  - name: install_licecap
    type: homebrew_cask
    package: licecap
    status: installed
  - name: install_alfred
    type: homebrew_cask
    package: alfred
    status: linked
  - name: symlink_zshrc
    type: symlink
    source: /Users/r7kamura/.zshrc
    destination: /Users/r7kamura/src/github.com/r7kamura/dotfiles/linked/.zshrc
    status: symlinked
  - name: clone_dotfiles
    type: git
    status: updated
    repository: git@github.com:r7kamura/dotfiles.git
    path: /Users/r7kamura/src/github.com/r7kamura/dotfiles
