hosts:
  - localhost
ssh: false
resources:
  - name: install_mysql
    type: homebrew
    package: mysql
  - name: install_redis
    type: homebrew
    package: redis
  - name: install_licecap
    type: homebrew_cask
    package: licecap
  - name: install_alfred
    type: homebrew_cask
    package: alfred
  - name: clone_dotfiles
    type: git
    repository: git@github.com:r7kamura/dotfiles.git
    path: /Users/r7kamura/src/github.com/r7kamura/dotfiles
  - name: symlink_zshrc
    type: symlink
    source: /Users/r7kamura/.zshrc
    destination: /Users/r7kamura/src/github.com/r7kamura/dotfiles/linked/.zshrc
  - name: put_zshrc
    type: file
    source: /Users/r7kamura/src/github.com/r7kamura/dotfiles/linked/.zshrc
    destination: /Users/r7kamura/src/github.com/r7kamura/dotfiles/linked/.zshrc
    user: r7kamura
    group: staff
